nginx-logstash:
  image: 'friddle/oss_logstash'
  restart: always
  environment:
    - LANG=C.UTF-8
    - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre
    - LOGSTASH_MAJOR=2.3
    - LS_SETTINGS_DIR=/etc/logstash
    - OSSTYPE=nginx
    - ENDPOINT=oss-cn-hangzhou-internal.aliyuncs.com
    - ACCESS_KEY_SECRET=<SECRET_KEY>
    - ACCESS_KEY_ID=<SECRET_ID>
    - BUCKET=<BUCKET>
    - PREFIX=<PREFIX>
    - INDEX=<INDEX>
    - COMPRESSION_TYPE=<SNAPPY:NONE>
    - LOGTYPE=<LOGTYPE>
  labels:
    aliyun.scale: '1'
  links:
    - elasticsearch
  volumes:
    - '/tmp/logstash:/tmp/logstash'
    - '/tmp/logstash-input-oss-tomcat:/root/.logstash-input-oss'
  
elasticsearch:
  image: elasticsearch:latest
  volumes:
    - /data/:/usr/share/elasticsearch/data
  expose:
      - "9200"
  command: elasticsearch -Des.network.host=0.0.0.0

kibana:
  image: friddle/kibana
  expose:
      - "5601"
  links:
    - elasticsearch
